# Generated by Django 4.1.1 on 2022-10-12 00:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jobs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('desctiption', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('adress', models.CharField(max_length=100, null=True)),
                ('jobType', models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporaty'), ('Phd', 'Phd')], default='Permanent', max_length=45)),
                ('education', models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Phd', 'Phd')], default='Bachelors', max_length=45)),
                ('industry', models.CharField(choices=[('Busness', 'Business'), ('Information Technilogy', 'It'), ('Education', 'Education'), ('Others', 'Others')], default='Busness', max_length=45)),
                ('experience', models.CharField(choices=[('No experience', 'No Experience'), ('1 Year', 'One Year'), ('2 Year', 'Two Year'), ('3 Years above', 'Three Years Plus')], default='No experience', max_length=45)),
                ('salary', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)])),
                ('company', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('last_date', models.DateTimeField(default=jobs.models.return_date)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
